version: '3'
services:
  redis-node1:
    image: redis:latest
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--cluster-announce-ip", "redis-node1"]
    ports:
      - "${REDIS_PORT_1}:6379"
    volumes:
      - redis-data1:/data
    networks:
      - net

  redis-node2:
    image: redis:latest
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--cluster-announce-ip", "redis-node2"]
    ports:
      - "${REDIS_PORT_2}:6379"
    volumes:
      - redis-data2:/data
    networks:
      - net

  redis-node3:
    image: redis:latest
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--cluster-announce-ip", "redis-node3"]
    ports:
      - "${REDIS_PORT_3}:6379"
    volumes:
      - redis-data3:/data
    networks:
      - net    

  redis-cluster-init:
    image: redis:latest
    command: ["sh", "-c", "sleep 5 && echo 'yes' | redis-cli --cluster create redis-node1:6379 redis-node2:6379 redis-node3:6379 --cluster-replicas 0"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
    networks:
      - net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - net

volumes:
  redis-data1:
  redis-data2:
  redis-data3:

networks:
  net:
    driver: bridge